### ISSUE TITLE
Port plotting functions to `python`

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/bitinformation_pipeline#16]
Overview: 
- [x] Fig. 2 #19 
- [ ] Fig. 3 seems to work nice with an `xr_bitround` wrapper 
- [x] Fig. SI 1: #59 

--- 
The plotting function gives a great overview about the information content present in each bit of a variable.
The port of the function to python should be straight forward and should be preferred over a further call of to Julia.

**Comment by milankl** [comment]
> The port of the function to python should be straight forward and should be preferred over a further call of to Julia.

I agree, especially given that I've written it with PyPlot. Only very few changes should be necessary for direct matplotlib syntax

**Comment by observingClouds** [comment]
Figure 2 is now supported. The ability to reproduce Fig. S1 would be still cool of course.

**Comment by aaronspring** [comment]
I have the code for fig s1 somewhere also
