### ISSUE TITLE
Bitround in python or julia

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/bitinformation_pipeline#25]
is `xr_bitround` the bitround from xarray as discussed [here](https://github.com/zarr-developers/numcodecs/issues/298)? For performance I'd suggest to use `round` from BitInformation. I've never actually compared the speed, but recalculation of constants is avoided reaching 16GB/s at which point it's memory-bound (and therefore likely an upper bound). Also gives us more flexibility in case we want to change something on the rounding front. 

__Originally posted by @milankl in https://github.com/observingClouds/bitinformation_pipeline/pull/21#discussion_r843996664__

**Comment by milankl** [comment]
For comparison, BitInformation.jl on my MacBook reaches
```julia
julia> using BitInformation,BenchmarkTools

julia> A = rand(Float32,1000,1000);

julia> B = rand(Float64,1000,1000);

julia> @btime round!($A,7);
  119.985 μs (0 allocations: 0 bytes)

julia> @btime round!($B,7);
  384.378 μs (0 allocations: 0 bytes)

julia> sizeof(A)/1000^2/120e-6
33333.333333333336

julia> sizeof(B)/1000^2/385e-6
20779.22077922078
```
so about 33GB/s for Float32, 21GB/s for Float64 in-place rounding. With memory allocations (`round!` is in-place, `round` creates a copy of the array and rounds that one instead) this drops to about 8GB/s for both Float32 and Float64
```julia
julia> @btime round($A,7);
  461.728 μs (2 allocations: 3.81 MiB)

julia> @btime round($B,7);
  1.019 ms (2 allocations: 7.63 MiB)

julia> sizeof(A)/1000^2/460e-6
8695.652173913044

julia> sizeof(B)/1000^2/1020e-6
7843.137254901961
```

**Comment by aaronspring** [comment]
how does the julia version handle lazy or out-of-memory data? Imagine I'd want to bitround 1 TB, which is larger than memory often.

**Comment by aaronspring** [comment]
can confirm that bitround.round is faster than xr_bitround despite the julia-python wrapping

**Comment by milankl** [comment]
> how does the julia version handle lazy or out-of-memory data? Imagine I'd want to bitround 1 TB, which is larger than memory often, that should work with xarray and dask

At the moment the round function is written for `::AbstractArray` in BitInformation.jl which means it'll accept any type that's a subtype of AbstractArray. The function itself does not hardcode how to access elements of such an array, i.e. whether you load everything into ram or keep things lazy isn't prescribed in `BitInformation.round`. I don't know how the interfaces work between python arrays that support lazy reading and julia, but from the Julia side this should automatically supported. Rounding is also a trivial in parallel, so you can go for any chunking you like.

**Comment by milankl** [comment]
> can confirm that bitround.round is faster than xr_bitround despite the julia-python wrapping

Could you provide some timings, I'm curious.

**Comment by milankl** [comment]
Also note that the zarr bitround @rabernat's PR https://github.com/zarr-developers/numcodecs/pull/299 only contains float32 at the moment. `BitInformation.round` supports Float64/32/16 (and any other float type if you define it as `<:Base.IEEEFloat`  and add methods for `Base.significand_mask(::MyFloatType)` and `Base.significand_bits(::MyFloatType)`)

**Comment by aaronspring** [comment]
we should definitely use `jl_bitround` as default

**Comment by aaronspring** [comment]
for chunked data with `dask`, the julia wrapper doesnt work, see https://github.com/observingClouds/bitinformation_pipeline/pull/47
