### ISSUE TITLE
keepbits or keepmantissabits

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/bitinformation_pipeline#27]
We don't document this very clear. 
There is a shift of 9: keepbits - 9 = keepmantissabits

keepmantissabits: shown in plot_bitinformation and used in xr_bitround
keepbits: output of get_keepbits, set as attrs in xr_bitround

hamocc_2d: https://gist.github.com/aaronspring/9a373397b830c2212c7c4bccaf500a48
mpiom_2d: https://gist.github.com/aaronspring/f3d1012bed2e0ac5b6f0974cb849e598
pwd: `/home/m/m300524/bitinformation_pipeline/examples`

**Comment by milankl** [comment]
Not the -9 is for Float32 only, for Float64 it would be -12 for Float16 -6

**Comment by aaronspring** [comment]
Now xr_bitround and jl_bitround use keepbits and not keep mantissa bits

**Comment by milankl** [comment]
Also probably apologies from my side, I know in BitInformation.jl only `keepbits` is used while its meaning is the number of mantissa bits that are kept, so technically it should be called `keepmantissabits`. I find it easier to think for rounding in terms of mantissa bits as keep(mantissa)bits=5 has then the same meaning across Float64/32/16

**Comment by aaronspring** [comment]
Need to change that here. Currently using keepbits

**Comment by aaronspring** [comment]
lets return mantissabits from `get_keepbits`

**Comment by aaronspring** [comment]
how does `get_keepbits` know about the `dtype`? either we provide `ds` or we store `dtype` in `info_per_bit` or we use the length of the `info_per_bit` array (if we do that, how to we differentiate between `Int` and `Float` types?)
