### ISSUE TITLE
`get_bitinformation(dim/axis)` in julia or python notation?

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/bitinformation_pipeline#31]
`bp.get_bitinformation` has a `dim` keyword.

Currently it accepts `str` and understands them as dimension names and it also accepts `int` to pass them on to `bitinformation.bitinformation` in julia. However in julia dimensions start with `1` and axis start with `0` in python.

I suggest to add internally `+1` if `dim` is `int` mimicking python behaviour. Or we implement `axis` additionally, which would be more correct name for what I propose.

**Comment by observingClouds** [comment]
I like the idea to have `axis` in addition to `dim`. It would feel more natural for people working in the PyData environment.
We should keep #22 in mind though.

**Comment by aaronspring** [comment]
https://xarray.pydata.org/en/stable/generated/xarray.DataArray.mean.html has `axis`, https://xarray.pydata.org/en/stable/generated/xarray.Dataset.mean.html doesnt.

when having `axis` and `dim`, they are mutually exclusive.

**Comment by observingClouds** [comment]
Yes, why not allowing `dim` to only be of type `str` and add `axis` which allows only `ints`. If no `dim` or `axis` is provided I would suggest to reduce over all dimensions/ axes as well.

**Comment by aaronspring** [comment]
And for axis, to we follow python first 0 or Julia first 1 conventions? I prefer python here

**Comment by observingClouds** [comment]
I prefer the pythonic way here as well.

**Comment by milankl** [comment]
Yeah, in the python interface go for python logic but the interface should translate to Julia logic
