### ISSUE TITLE
Make maskinfo optional

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/bitinformation_pipeline#38]
For large datasets `get_keepbits` is tremendously slowed down by the calculation of the mask for each individual variable

```python
 "maskinfo": int(ds[var].notnull().sum())
```

We could make the mask an argument or get it somehow from `get_bitinformation`. But I would argue we follow Milan's advice https://github.com/observingClouds/bitinformation_pipeline/issues/17#issuecomment-1088547497 and remove this part from the code.

**Comment by aaronspring** [comment]
I'd vote to remove maskinfo alltogether.

**Comment by milankl** [comment]
Since BitInformation.jl v0.5 you can call `bitinformation(A::AbstractArray{T},masked_value::T)` which creates internally a mask for array `A` based on `masked_value`. Otherwise could you elaborate what "tremendously slow" means?

**Comment by aaronspring** [comment]
Slow refers to the xarray side checking how many values are masked for that large icon output. This is the problem of how this output is stored and read in, classic IO.
