### ISSUE TITLE
Orchestrate for multiple files

### ISSUE THREAD

**Issue by aaronspring** [observingClouds/bitinformation_pipeline#44]
Run get_bitinformation and get_keepbits once and apply bitround to multiple files. 

How to run in a script in parallel?
try prefect https://docs.prefect.io/core/concepts/persistence.html#output-caching-based-on-a-file-target pangeo_forge_recipes/executors/prefect.py

**Comment by aaronspring** [comment]
dask path: loop or map https://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_netcdf.html compute False and finally client.compute. Test with dashboard https://pypi.org/project/dask-labextension/

**Comment by aaronspring** [comment]
first draft: https://gist.github.com/aaronspring/aef0f682614f43f6b85fcf14c7edf08c

todo:
- [ ] scale on supercomputer
- [ ] integrate `get_bitinformation`
- [ ] wrapper for MPI-ESM experiment structure

**Comment by aaronspring** [comment]
- [ ] Test whether bitrounding works even for MPIESM grb

**Comment by observingClouds** [comment]
See my comment in #67. The GRIB file format does not really support a suitable compression algorithm. Converting GRIB files to zarr via bitinformation and compression would be suitable though if no lossy compression has been applied to the GRIB files before. Any lossy compression might have an influence on the detection of the information content.
