### ISSUE TITLE
Memory potentially not deallocated correctly when calling get_bitinformation

### ISSUE THREAD

**Issue by observingClouds** [observingClouds/bitinformation_pipeline#55]
### Description

Running `get_bitinformation` on a "large" dataset with several variables on a Dask LocalCluster results in high memory usage that accumulates during the loop over the individual variables.

Warnings like the following occur until the workers run out of memory:

```
distributed.worker - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be
released to the OS; see https://distributed.dask.org/en/latest/worker.html#memtrim for more information. -- Unmanaged 
memory: 11.13 GiB -- Worker memory limit: 15.72 GiB
```

**Comment by aaronspring** [comment]
What was the dataset size, individual variable size and chunkier where this occurred?
